# Generated by Django 3.1 on 2021-04-09 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrackProgressCourseBatch',
            new_name='TrackProgressBatchCourse',
        ),
    ]
