# Generated by Django 3.2 on 2021-04-09 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210409_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_hod',
            new_name='is_principal',
        ),
    ]
