# Generated by Django 3.2 on 2021-04-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210409_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='department',
        ),
        migrations.AddField(
            model_name='batch',
            name='in_class',
            field=models.IntegerField(default=None, max_length=12),
        ),
        migrations.AddField(
            model_name='batch',
            name='section',
            field=models.CharField(default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='department',
            field=models.IntegerField(choices=[(1, 'Mathematics'), (2, 'English'), (3, 'Hindi'), (4, 'Science')], default=1),
        ),
    ]
