# Generated by Django 3.2 on 2021-04-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210410_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='in_class',
            field=models.IntegerField(default=None),
        ),
    ]
