# Generated by Django 3.2 on 2021-04-09 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210410_0023'),
        ('account', '0006_alter_batch_in_class'),
    ]

    operations = [
    ]
