# Generated by Django 3.2 on 2021-04-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20210410_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.TextField(choices=[('MATH', 'Mathematics'), ('ENG', 'English'), ('HINDI', 'Hindi'), ('SCI', 'Science')], default=1),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='department',
            field=models.TextField(choices=[('MATH', 'Mathematics'), ('ENG', 'English'), ('HINDI', 'Hindi'), ('SCI', 'Science')], default=1),
        ),
    ]
