# Generated by Django 3.2 on 2021-04-10 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210410_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='class_no',
            field=models.IntegerField(),
        ),
    ]
