# Generated by Django 3.2 on 2021-04-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20210410_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_batchRepresntative',
            field=models.BooleanField(default=False),
        ),
    ]
