# Generated by Django 3.1 on 2021-04-10 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20210410_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackprogressbatchcourse',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='trackprogressbatchcourse',
            name='start_date',
        ),
    ]
