# Generated by Django 3.1 on 2021-04-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20210410_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='ideallecture',
            field=models.IntegerField(default=5),
        ),
    ]
