# Generated by Django 3.2 on 2021-04-10 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0013_studentprofile_is_batchrepresntative'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants_CR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateregisteres', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.studentprofile')),
            ],
        ),
    ]
